<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Npi.Loader</RootNamespace>
    <UserSecretsId>getnpidata-loader</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Npi.Core\Npi.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Npi.Loader.Tests" />
  </ItemGroup>

</Project>
