<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Npi.Core</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CsvHelper" />
    <PackageReference Include="Dapper" />
    <PackageReference Include="MySqlConnector" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Npi.Core.Tests" />
    <InternalsVisibleTo Include="Npi.Loader.Tests" />
  </ItemGroup>

</Project>
